/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JBuscarCliente.java
 *
 * Created on 22/11/2011, 19:45:22
 */
package gui.pizzaria;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.PreparedStatement;
import dados.pizzaria.ConectaBanco;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Hugo Santos
 */
public class JBuscarCliente extends javax.swing.JPanel {

    /** Creates new form JBuscarCliente */
    public JBuscarCliente() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        playout = new javax.swing.JPanel();
        ltitulo = new javax.swing.JLabel();
        playout2 = new javax.swing.JPanel();
        lcodigo1 = new javax.swing.JLabel();
        tcliente1 = new javax.swing.JTextField();
        buscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        playout.setBackground(new java.awt.Color(102, 102, 255));

        ltitulo.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 36));
        ltitulo.setText("Buscar Clientes");

        javax.swing.GroupLayout playoutLayout = new javax.swing.GroupLayout(playout);
        playout.setLayout(playoutLayout);
        playoutLayout.setHorizontalGroup(
            playoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(playoutLayout.createSequentialGroup()
                .addGap(196, 196, 196)
                .addComponent(ltitulo)
                .addContainerGap(234, Short.MAX_VALUE))
        );
        playoutLayout.setVerticalGroup(
            playoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, playoutLayout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(ltitulo)
                .addGap(22, 22, 22))
        );

        playout2.setBackground(new java.awt.Color(102, 102, 255));

        javax.swing.GroupLayout playout2Layout = new javax.swing.GroupLayout(playout2);
        playout2.setLayout(playout2Layout);
        playout2Layout.setHorizontalGroup(
            playout2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 592, Short.MAX_VALUE)
        );
        playout2Layout.setVerticalGroup(
            playout2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 19, Short.MAX_VALUE)
        );

        lcodigo1.setText("Nome Cliente:");

        buscar.setText("Buscar");
        buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "cod", "nome"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(playout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 526, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lcodigo1)
                        .addGap(18, 18, 18)
                        .addComponent(tcliente1, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                        .addComponent(buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(32, 32, 32))
            .addComponent(playout2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(playout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lcodigo1)
                    .addComponent(tcliente1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscar))
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(playout2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 592, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 335, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

private void buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarActionPerformed

    preencher2();
    // TODO add your handling code here:
}//GEN-LAST:event_buscarActionPerformed

private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
int linha = jTable1.getSelectedRow();
//seleciona um linha na tabela  
JCadReserva.nome_cliente.setText(jTable1.getValueAt(linha, 1).toString());
FBuscarCliente.getinstacia().setVisible(false);

// TODO add your handling code here:
}//GEN-LAST:event_jTable1MouseClicked
public void preencher2() {//preencher a tabela com dados de busca

        DefaultTableModel tab = (DefaultTableModel) jTable1.getModel();
        tab.setNumRows(0);

        try {
            Connection con = (Connection) ConectaBanco.getConexao();
            
            PreparedStatement pstmt;
            pstmt = (PreparedStatement) con.prepareStatement("select codigo,nome from clientes where nome like ?" );

            pstmt.setString(1, "%" + tcliente1.getText() + "%" );
            
            ResultSet rs = pstmt.executeQuery();
            
            while (rs.next()){
                int codigo = rs.getInt("codigo");
                String nome = rs.getString("nome");
            tab.addRow(new Object[]{new Integer(codigo),nome});
            }

            pstmt.close();

        } catch (SQLException e) {
            System.out.println("ERRO" + e);
        }

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buscar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lcodigo1;
    private javax.swing.JLabel ltitulo;
    private javax.swing.JPanel playout;
    private javax.swing.JPanel playout2;
    private javax.swing.JTextField tcliente1;
    // End of variables declaration//GEN-END:variables
}
