/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JBuscarMesas.java
 *
 * Created on 22/11/2011, 13:58:58
 */
package gui.pizzaria;

import java.sql.*;
import javax.swing.table.DefaultTableModel;
import com.mysql.jdbc.Connection;
import dados.pizzaria.ConectaBanco;
/**
 *
 * @author Hugo Santos
 */
public class JBuscarMesas extends javax.swing.JPanel {

    /** Creates new form JBuscarMesas */
    public JBuscarMesas() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        playout = new javax.swing.JPanel();
        ltitulo = new javax.swing.JLabel();
        lnumero = new javax.swing.JLabel();
        tmesa = new javax.swing.JTextField();
        buscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        playout2 = new javax.swing.JPanel();

        playout.setBackground(new java.awt.Color(102, 102, 255));

        ltitulo.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 36));
        ltitulo.setText("Buscar Mesa");

        javax.swing.GroupLayout playoutLayout = new javax.swing.GroupLayout(playout);
        playout.setLayout(playoutLayout);
        playoutLayout.setHorizontalGroup(
            playoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(playoutLayout.createSequentialGroup()
                .addGap(196, 196, 196)
                .addComponent(ltitulo)
                .addContainerGap(256, Short.MAX_VALUE))
        );
        playoutLayout.setVerticalGroup(
            playoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, playoutLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ltitulo)
                .addContainerGap())
        );

        lnumero.setText("Numero Mesa:");

        buscar.setText("Buscar");
        buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Numero", "Tipo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        playout2.setBackground(new java.awt.Color(102, 102, 255));

        javax.swing.GroupLayout playout2Layout = new javax.swing.GroupLayout(playout2);
        playout2.setLayout(playout2Layout);
        playout2Layout.setHorizontalGroup(
            playout2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 584, Short.MAX_VALUE)
        );
        playout2Layout.setVerticalGroup(
            playout2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(playout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 498, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lnumero)
                        .addGap(18, 18, 18)
                        .addComponent(tmesa, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(42, 42, 42))
            .addComponent(playout2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(playout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lnumero)
                    .addComponent(tmesa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscar))
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(playout2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

private void buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarActionPerformed

    preencher1();//preenche a tabela com o resultados de busca
    // TODO add your handling code here:
}//GEN-LAST:event_buscarActionPerformed

private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked

    int linha = jTable1.getSelectedRow();
    //seleciona um linha na tabela e enviar os dados para um novo formulario
JCadPedido.tnumeromesa.setText(jTable1.getValueAt(linha, 0).toString());
JCadPedido.ttipomesa.setText(jTable1.getValueAt(linha, 1).toString());
FBuscarMesas.getinstacia().setVisible(false);
// TODO add your handling code here:
}//GEN-LAST:event_jTable1MouseClicked

public void preencher1() {  //busca os dados de mesas

        DefaultTableModel tab = (DefaultTableModel) jTable1.getModel();
        tab.setNumRows(0);

        try {
            Connection con = (Connection) ConectaBanco.getConexao();
            
            PreparedStatement pstmt;
            pstmt = con.prepareStatement("select numero,tipo from mesas where numero like ?" );

            pstmt.setString(1, "%" + tmesa.getText() + "%" );
            
            ResultSet rs = pstmt.executeQuery();
            
            while (rs.next()){
                int numero = rs.getInt("Numero");
                String tipo = rs.getString("Tipo");
            tab.addRow(new Object[]{new Integer(numero),tipo});
            }

            pstmt.close();

        } catch (SQLException e) {
            System.out.println("ERRO" + e);
        }
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buscar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lnumero;
    private javax.swing.JLabel ltitulo;
    private javax.swing.JPanel playout;
    private javax.swing.JPanel playout2;
    private javax.swing.JTextField tmesa;
    // End of variables declaration//GEN-END:variables
}
