/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JCadItens_Cardapios.java
 *
 * Created on 13/11/2011, 18:03:53
 */
package gui.pizzaria;

import br.pizzaria.Itens_Cardapios;
import dados.pizzaria.ConectaBanco;
import dados.pizzaria.Itens_CardapiosDao;
import dados.pizzaria.PizzariaDao;
import javax.swing.JOptionPane;

/**
 *
 * @author Saulo Francisco
 */
public class JCadIten_Cardapio extends javax.swing.JPanel {

    /** Creates new form JCadItens_Cardapios */
    public JCadIten_Cardapio() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        playout = new javax.swing.JPanel();
        ltitulo = new javax.swing.JLabel();
        playout2 = new javax.swing.JPanel();
        lnome = new javax.swing.JLabel();
        nome = new javax.swing.JTextField();
        ldescricao = new javax.swing.JLabel();
        descricao = new javax.swing.JTextField();
        lvalor = new javax.swing.JLabel();
        valor = new javax.swing.JTextField();
        bcancelar = new javax.swing.JButton();
        bsalvar = new javax.swing.JButton();
        blimpar = new javax.swing.JButton();

        playout.setBackground(new java.awt.Color(102, 102, 255));

        ltitulo.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 36));
        ltitulo.setText("    Cadastro Itens Cardápio");

        javax.swing.GroupLayout playoutLayout = new javax.swing.GroupLayout(playout);
        playout.setLayout(playoutLayout);
        playoutLayout.setHorizontalGroup(
            playoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(playoutLayout.createSequentialGroup()
                .addGap(176, 176, 176)
                .addComponent(ltitulo)
                .addContainerGap(167, Short.MAX_VALUE))
        );
        playoutLayout.setVerticalGroup(
            playoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, playoutLayout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addComponent(ltitulo)
                .addGap(28, 28, 28))
        );

        playout2.setBackground(new java.awt.Color(102, 102, 255));

        javax.swing.GroupLayout playout2Layout = new javax.swing.GroupLayout(playout2);
        playout2.setLayout(playout2Layout);
        playout2Layout.setHorizontalGroup(
            playout2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 627, Short.MAX_VALUE)
        );
        playout2Layout.setVerticalGroup(
            playout2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 26, Short.MAX_VALUE)
        );

        lnome.setText("Nome");

        nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeActionPerformed(evt);
            }
        });

        ldescricao.setText("Descrição");

        descricao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                descricaoActionPerformed(evt);
            }
        });

        lvalor.setText("Valor");

        valor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valorActionPerformed(evt);
            }
        });

        bcancelar.setText("Cancelar");
        bcancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bcancelarActionPerformed(evt);
            }
        });

        bsalvar.setText("Salvar");
        bsalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsalvarActionPerformed(evt);
            }
        });

        blimpar.setText("Limpar");
        blimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blimparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(playout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(playout2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(bcancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62)
                        .addComponent(bsalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(blimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lnome)
                            .addComponent(ldescricao)
                            .addComponent(lvalor))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(descricao)
                            .addComponent(nome, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 531, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(valor, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(playout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lnome)
                    .addComponent(nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ldescricao)
                    .addComponent(descricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lvalor)
                    .addComponent(valor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bcancelar)
                    .addComponent(bsalvar)
                    .addComponent(blimpar))
                .addGap(18, 18, 18)
                .addComponent(playout2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

private void nomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_nomeActionPerformed

private void descricaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_descricaoActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_descricaoActionPerformed

private void valorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valorActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_valorActionPerformed

private void bcancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bcancelarActionPerformed
// TODO add your handling code here:
    FCadIten_Cardapio.getinstacia().setVisible(false);
}//GEN-LAST:event_bcancelarActionPerformed

private void bsalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsalvarActionPerformed
// TODO add your handling code here:
    Itens_CardapiosDao icDao = PizzariaDao.novoItens_CardapiosDao();
   Itens_Cardapios ic = new Itens_Cardapios();
         //cadastrando o produto do cardapio no banco de dados
         ic.setNome(nome.getText());
         ic.setDescricao(descricao.getText());
         ic.setValor(Float.parseFloat(valor.getText()));
         
          ConectaBanco.setBanco(ConectaBanco.MYSQL);
    int codigo = icDao.criar(ic);
    ic.setCodigo(codigo);
    JOptionPane.showMessageDialog(null, "ITEM CARDAPIO CADASTRADO!");
}//GEN-LAST:event_bsalvarActionPerformed

private void blimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blimparActionPerformed
// TODO add your handling code here:
    //limpando campos
        nome.setText(" ");
        descricao.setText(" ");
        valor.setText(""); 
}//GEN-LAST:event_blimparActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bcancelar;
    private javax.swing.JButton blimpar;
    private javax.swing.JButton bsalvar;
    private javax.swing.JTextField descricao;
    private javax.swing.JLabel ldescricao;
    private javax.swing.JLabel lnome;
    private javax.swing.JLabel ltitulo;
    private javax.swing.JLabel lvalor;
    private javax.swing.JTextField nome;
    private javax.swing.JPanel playout;
    private javax.swing.JPanel playout2;
    private javax.swing.JTextField valor;
    // End of variables declaration//GEN-END:variables
}
