/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JCadPedido.java
 *
 * Created on 21/11/2011, 22:01:01
 */
package gui.pizzaria;

import br.pizzaria.Itens_Pedidos;
import br.pizzaria.Pedidos;
import com.mysql.jdbc.Connection;
import com.mysql.jdbc.PreparedStatement;
import dados.pizzaria.ConectaBanco;
import dados.pizzaria.Itens_PedidosDao;
import dados.pizzaria.PedidosDao;
import dados.pizzaria.PizzariaDao;

import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Hugo Santos
 */
public class JCadPedido extends javax.swing.JPanel {

    int a;
    /** Creates new form JCadPedido */
    public JCadPedido() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        playout = new javax.swing.JPanel();
        ltitulo = new javax.swing.JLabel();
        playout2 = new javax.swing.JPanel();
        lnomecliente = new javax.swing.JLabel();
        tnomecliente = new javax.swing.JTextField();
        buscarcliente = new javax.swing.JButton();
        lnumeromesa = new javax.swing.JLabel();
        tnumeromesa = new javax.swing.JTextField();
        buscarmesa = new javax.swing.JButton();
        ldescricao = new javax.swing.JLabel();
        tdescricao = new javax.swing.JTextField();
        ldata = new javax.swing.JLabel();
        tdata = new javax.swing.JTextField();
        lhora = new javax.swing.JLabel();
        thora = new javax.swing.JTextField();
        limpar = new javax.swing.JButton();
        salvar = new javax.swing.JButton();
        fechar = new javax.swing.JButton();
        lcodigocliente = new javax.swing.JLabel();
        tcodigocliente = new javax.swing.JTextField();
        ltipomesa = new javax.swing.JLabel();
        ttipomesa = new javax.swing.JTextField();

        playout.setBackground(new java.awt.Color(102, 102, 255));

        ltitulo.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 36));
        ltitulo.setText("Cadastro de Pedidos");

        javax.swing.GroupLayout playoutLayout = new javax.swing.GroupLayout(playout);
        playout.setLayout(playoutLayout);
        playoutLayout.setHorizontalGroup(
            playoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(playoutLayout.createSequentialGroup()
                .addGap(169, 169, 169)
                .addComponent(ltitulo)
                .addContainerGap(140, Short.MAX_VALUE))
        );
        playoutLayout.setVerticalGroup(
            playoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(playoutLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(ltitulo)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        playout2.setBackground(new java.awt.Color(102, 102, 255));

        javax.swing.GroupLayout playout2Layout = new javax.swing.GroupLayout(playout2);
        playout2.setLayout(playout2Layout);
        playout2Layout.setHorizontalGroup(
            playout2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 526, Short.MAX_VALUE)
        );
        playout2Layout.setVerticalGroup(
            playout2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 19, Short.MAX_VALUE)
        );

        lnomecliente.setText("Nome Cliente:");

        tnomecliente.setEditable(false);

        buscarcliente.setText("Buscar");
        buscarcliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarclienteActionPerformed(evt);
            }
        });

        lnumeromesa.setText("Numero Mesa:");

        tnumeromesa.setEditable(false);

        buscarmesa.setText("Buscar");
        buscarmesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarmesaActionPerformed(evt);
            }
        });

        ldescricao.setText("Descricao:");

        ldata.setText("Data:");

        lhora.setText("Hora:");

        limpar.setText("Limpar");
        limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limparActionPerformed(evt);
            }
        });

        salvar.setText("Salvar");
        salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarActionPerformed(evt);
            }
        });

        fechar.setText("Fechar");
        fechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fecharActionPerformed(evt);
            }
        });

        lcodigocliente.setText("Codigo Cliente:");

        tcodigocliente.setEditable(false);

        ltipomesa.setText("Tipo:");

        ttipomesa.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(playout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lcodigocliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tcodigocliente, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                        .addGap(10, 10, 10)
                        .addComponent(lnomecliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tnomecliente, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lnumeromesa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tnumeromesa, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)
                        .addComponent(ltipomesa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ttipomesa, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buscarmesa)
                    .addComponent(buscarcliente))
                .addGap(12, 12, 12))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(ldescricao)
                            .addGap(28, 28, 28)
                            .addComponent(tdescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(limpar, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(92, 92, 92)
                            .addComponent(salvar, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(91, 91, 91)
                            .addComponent(fechar, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ldata)
                        .addGap(28, 28, 28)
                        .addComponent(tdata, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(lhora)
                        .addGap(40, 40, 40)
                        .addComponent(thora, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(26, Short.MAX_VALUE))
            .addComponent(playout2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(playout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lnomecliente)
                    .addComponent(buscarcliente)
                    .addComponent(tnomecliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lcodigocliente)
                    .addComponent(tcodigocliente, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buscarmesa)
                    .addComponent(lnumeromesa)
                    .addComponent(tnumeromesa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ltipomesa)
                    .addComponent(ttipomesa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ldescricao)
                    .addComponent(tdescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ldata)
                    .addComponent(tdata, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lhora)
                    .addComponent(thora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(limpar)
                    .addComponent(salvar)
                    .addComponent(fechar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(playout2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

private void buscarclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarclienteActionPerformed

     FBuscaCliente.getinstacia().setVisible(true);
    // TODO add your handling code here:
}//GEN-LAST:event_buscarclienteActionPerformed

private void buscarmesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarmesaActionPerformed

    FBuscarMesas.getinstacia().setVisible(true);
    // TODO add your handling code here:
}//GEN-LAST:event_buscarmesaActionPerformed

private void limparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limparActionPerformed

    tnomecliente.setText(" ");
    tnumeromesa.setText(" ");
    //taprodutos.setText(" ");
    tdescricao.setText(" ");
    tdata.setText(" ");
    thora.setText(" ");
    
    // TODO add your handling code here:
}//GEN-LAST:event_limparActionPerformed

private void salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarActionPerformed
PedidosDao pDao = PizzariaDao.novoPedidosDao();
    
    Pedidos p = new Pedidos();
    // salvando os dados do pedido    
      p.setCliente(Integer.parseInt(tcodigocliente.getText()));
      p.setMesa(Integer.parseInt(tnumeromesa.getText()));     
      p.setDescricao(tdescricao.getText());
      p.setData(tdata.getText());
      p.setHora(thora.getText());
      
         
        ConectaBanco.setBanco(ConectaBanco.MYSQL);
        int codigo = pDao.criar(p);
        p.setCodigo(codigo);
        JOptionPane.showMessageDialog(null, "PEDIDO CADASTRADO!");
     //chamando o formulario Fprodutos para salva os produtos de um pedido 
        FProdutos.getinstacia().setVisible(true);
        FCadPedido.getinstacia().setVisible(false);
}//GEN-LAST:event_salvarActionPerformed

private void fecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fecharActionPerformed

    FCadPedido.getinstacia().setVisible(false);    // TODO add your handling code here:
}//GEN-LAST:event_fecharActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buscarcliente;
    private javax.swing.JButton buscarmesa;
    private javax.swing.JButton fechar;
    private javax.swing.JLabel lcodigocliente;
    private javax.swing.JLabel ldata;
    private javax.swing.JLabel ldescricao;
    private javax.swing.JLabel lhora;
    private javax.swing.JButton limpar;
    private javax.swing.JLabel lnomecliente;
    private javax.swing.JLabel lnumeromesa;
    private javax.swing.JLabel ltipomesa;
    private javax.swing.JLabel ltitulo;
    private javax.swing.JPanel playout;
    private javax.swing.JPanel playout2;
    private javax.swing.JButton salvar;
    public static javax.swing.JTextField tcodigocliente;
    private javax.swing.JTextField tdata;
    private javax.swing.JTextField tdescricao;
    private javax.swing.JTextField thora;
    public static javax.swing.JTextField tnomecliente;
    public static javax.swing.JTextField tnumeromesa;
    public static javax.swing.JTextField ttipomesa;
    // End of variables declaration//GEN-END:variables
}
