/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JCadMesa.java
 *
 * Created on 13/11/2011, 09:32:56
 */
package gui.pizzaria;

import br.pizzaria.Mesas;
import dados.pizzaria.ConectaBanco;
import dados.pizzaria.MesasDao;
import dados.pizzaria.PizzariaDao;
import javax.swing.JOptionPane;
/**
 *
 * @author Saulo Francisco
 */
public class JCadMesa extends javax.swing.JPanel {

    /** Creates new form JCadMesa */
    public JCadMesa() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        playout = new javax.swing.JPanel();
        ltitulo = new javax.swing.JLabel();
        playout2 = new javax.swing.JPanel();
        bfechar = new javax.swing.JButton();
        bsalvar = new javax.swing.JButton();
        blimpar = new javax.swing.JButton();
        lnumerocadeira = new javax.swing.JLabel();
        numerocadeira = new javax.swing.JTextField();
        ltipo = new javax.swing.JLabel();
        tipo = new javax.swing.JTextField();

        playout.setBackground(new java.awt.Color(102, 102, 255));

        ltitulo.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 36));
        ltitulo.setText("    Cadastro Mesas");

        javax.swing.GroupLayout playoutLayout = new javax.swing.GroupLayout(playout);
        playout.setLayout(playoutLayout);
        playoutLayout.setHorizontalGroup(
            playoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(playoutLayout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addComponent(ltitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(169, Short.MAX_VALUE))
        );
        playoutLayout.setVerticalGroup(
            playoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(playoutLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(ltitulo)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        playout2.setBackground(new java.awt.Color(102, 102, 255));

        javax.swing.GroupLayout playout2Layout = new javax.swing.GroupLayout(playout2);
        playout2.setLayout(playout2Layout);
        playout2Layout.setHorizontalGroup(
            playout2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 521, Short.MAX_VALUE)
        );
        playout2Layout.setVerticalGroup(
            playout2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 27, Short.MAX_VALUE)
        );

        bfechar.setText("Fechar");
        bfechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bfecharActionPerformed(evt);
            }
        });

        bsalvar.setText("Salvar");
        bsalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsalvarActionPerformed(evt);
            }
        });

        blimpar.setText("Limpar");
        blimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blimparActionPerformed(evt);
            }
        });

        lnumerocadeira.setText("Numeros de Cadeiras");

        numerocadeira.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numerocadeiraActionPerformed(evt);
            }
        });

        ltipo.setText("Tipo:");

        tipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ltipo)
                .addGap(18, 18, 18)
                .addComponent(tipo, javax.swing.GroupLayout.DEFAULT_SIZE, 410, Short.MAX_VALUE)
                .addGap(59, 59, 59))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bfechar, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(bsalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(blimpar, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lnumerocadeira)
                        .addGap(18, 18, 18)
                        .addComponent(numerocadeira, javax.swing.GroupLayout.DEFAULT_SIZE, 332, Short.MAX_VALUE)))
                .addGap(59, 59, 59))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                .addComponent(playout2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(playout, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(playout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ltipo)
                    .addComponent(tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lnumerocadeira)
                    .addComponent(numerocadeira, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bfechar)
                    .addComponent(blimpar)
                    .addComponent(bsalvar))
                .addGap(37, 37, 37)
                .addComponent(playout2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

private void bfecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bfecharActionPerformed
// TODO add your handling code here:
    FCadMesa.getinstacia().setVisible(false);
}//GEN-LAST:event_bfecharActionPerformed

private void bsalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsalvarActionPerformed
// TODO add your handling code here
    MesasDao mDao = PizzariaDao.novoMesasDao();
    Mesas m = new Mesas();
    //salvando os dados das mesas no bancos de dads.
    m.setTipo(tipo.getText());
    m.setNumero_cadeiras(Integer.parseInt(numerocadeira.getText()));
    
    ConectaBanco.setBanco(ConectaBanco.MYSQL);
    int numero = mDao.criar(m);
    m.setNumero(numero);
    JOptionPane.showMessageDialog(null, "MESA CADASTRADA!");
}//GEN-LAST:event_bsalvarActionPerformed

private void blimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blimparActionPerformed
// TODO add your handling code here:
     
}//GEN-LAST:event_blimparActionPerformed

private void numerocadeiraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numerocadeiraActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_numerocadeiraActionPerformed

private void tipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_tipoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bfechar;
    private javax.swing.JButton blimpar;
    private javax.swing.JButton bsalvar;
    private javax.swing.JLabel lnumerocadeira;
    private javax.swing.JLabel ltipo;
    private javax.swing.JLabel ltitulo;
    private javax.swing.JTextField numerocadeira;
    private javax.swing.JPanel playout;
    private javax.swing.JPanel playout2;
    private javax.swing.JTextField tipo;
    // End of variables declaration//GEN-END:variables
}
