/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JContinuaPedido.java
 *
 * Created on 25/11/2011, 15:54:05
 */
package gui.pizzaria;

import br.pizzaria.Itens_Pedidos;
import dados.pizzaria.ConectaBanco;
import dados.pizzaria.Itens_PedidosDao;
import dados.pizzaria.PizzariaDao;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Hugo Santos
 */
public class JContinuaPedido extends javax.swing.JPanel {

    /** Creates new form JContinuaPedido */
    public JContinuaPedido() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tcodigo1 = new javax.swing.JTextField();
        lcodigo = new javax.swing.JLabel();
        playout = new javax.swing.JPanel();
        ltitulo = new javax.swing.JLabel();
        tproduto1 = new javax.swing.JTextField();
        buscar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        salvar = new javax.swing.JButton();
        fechar = new javax.swing.JButton();
        playout2 = new javax.swing.JPanel();
        lpedido = new javax.swing.JLabel();
        tpedido1 = new javax.swing.JTextField();
        buscarpedido = new javax.swing.JButton();

        tcodigo1.setEditable(false);

        lcodigo.setText("Codigo:");

        playout.setBackground(new java.awt.Color(102, 102, 255));

        ltitulo.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 36));
        ltitulo.setText("Produtos");

        javax.swing.GroupLayout playoutLayout = new javax.swing.GroupLayout(playout);
        playout.setLayout(playoutLayout);
        playoutLayout.setHorizontalGroup(
            playoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(playoutLayout.createSequentialGroup()
                .addGap(151, 151, 151)
                .addComponent(ltitulo)
                .addContainerGap(234, Short.MAX_VALUE))
        );
        playoutLayout.setVerticalGroup(
            playoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, playoutLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ltitulo))
        );

        tproduto1.setEditable(false);

        buscar.setText("Buscar");
        buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarActionPerformed(evt);
            }
        });

        jLabel2.setText("Produto:");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Produto"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        salvar.setText("Salvar");
        salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarActionPerformed(evt);
            }
        });

        fechar.setText("Fechar");
        fechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fecharActionPerformed(evt);
            }
        });

        playout2.setBackground(new java.awt.Color(102, 102, 255));

        javax.swing.GroupLayout playout2Layout = new javax.swing.GroupLayout(playout2);
        playout2.setLayout(playout2Layout);
        playout2Layout.setHorizontalGroup(
            playout2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 479, Short.MAX_VALUE)
        );
        playout2Layout.setVerticalGroup(
            playout2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        lpedido.setText("Codigo Pedido:");

        tpedido1.setEditable(false);

        buscarpedido.setText("Buscar");
        buscarpedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarpedidoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(playout2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(playout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 459, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(salvar, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 108, Short.MAX_VALUE)
                        .addComponent(fechar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lcodigo)
                        .addGap(18, 18, 18)
                        .addComponent(tcodigo1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tproduto1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                        .addComponent(buscar)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lpedido)
                .addGap(18, 18, 18)
                .addComponent(tpedido1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 214, Short.MAX_VALUE)
                .addComponent(buscarpedido)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(playout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lpedido)
                            .addComponent(tpedido1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buscarpedido)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(buscar)
                        .addComponent(lcodigo)
                        .addComponent(tcodigo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2))
                    .addComponent(tproduto1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(salvar)
                    .addComponent(fechar))
                .addGap(18, 18, 18)
                .addComponent(playout2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

private void buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarActionPerformed

    FBuscaProduto.getinstacia().setVisible(true);
    
    
    // TODO add your handling code here:
}//GEN-LAST:event_buscarActionPerformed

private void salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarActionPerformed

    inserir(); // função para inserir os produtos no banco de dados
    preencher3();  //função para preencher campos da tabela
    
    // TODO add your handling code here:
}//GEN-LAST:event_salvarActionPerformed

private void fecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fecharActionPerformed

   FContinuaPedido.getinstacia().setVisible(false);
    // TODO add your handling code here:
}//GEN-LAST:event_fecharActionPerformed

private void buscarpedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarpedidoActionPerformed

    FBuscarPedido.getinstacia().setVisible(true);
    // TODO add your handling code here:
}//GEN-LAST:event_buscarpedidoActionPerformed
public void preencher3(){
    DefaultTableModel modelo = (DefaultTableModel)JContinuaPedido.jTable1.getModel();
       //preenchendo a tabela com os dados
    modelo.addRow(new Object[]{tcodigo1.getText(),tproduto1.getText()});
}
public void inserir(){
    Itens_PedidosDao ipDao = PizzariaDao.novoItens_PedidosDao();
    Itens_Pedidos ip = new Itens_Pedidos();

    //salvando os produtos para um detrminado prduto no banco de dados
    ip.setQuantdade(1);
    ip.setPedido(Integer.parseInt(tpedido1.getText()));
    ip.setItens_cardapio(Integer.parseInt(tcodigo1.getText()));
    ConectaBanco.setBanco(ConectaBanco.MYSQL);
    int codigo = ipDao.criar(ip);
    ip.setCodigo(codigo);           
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buscar;
    private javax.swing.JButton buscarpedido;
    private javax.swing.JButton fechar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable jTable1;
    private javax.swing.JLabel lcodigo;
    private javax.swing.JLabel lpedido;
    private javax.swing.JLabel ltitulo;
    private javax.swing.JPanel playout;
    private javax.swing.JPanel playout2;
    private javax.swing.JButton salvar;
    public static javax.swing.JTextField tcodigo1;
    public static javax.swing.JTextField tpedido1;
    public static javax.swing.JTextField tproduto1;
    // End of variables declaration//GEN-END:variables
}
