/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JFinalizarPedido.java
 *
 * Created on 23/11/2011, 14:20:26
 */
package gui.pizzaria;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.PreparedStatement;
import dados.pizzaria.ConectaBanco;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Hugo Santos
 */
public class JFinalizarPedido extends javax.swing.JPanel {

    int li;
    /** Creates new form JFinalizarPedido */
    public JFinalizarPedido() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        lpedido = new javax.swing.JLabel();
        tpedido = new javax.swing.JTextField();
        buscarpedido = new javax.swing.JButton();
        playout = new javax.swing.JPanel();
        ltitulo = new javax.swing.JLabel();
        playout2 = new javax.swing.JPanel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Nome Cliente", "Numero Mesa", "Descricao", "Produto", "Hora", "Data"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        lpedido.setText("Numero da Mesa:");

        buscarpedido.setText("Buscar");
        buscarpedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarpedidoActionPerformed(evt);
            }
        });

        playout.setBackground(new java.awt.Color(102, 102, 255));

        ltitulo.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 36));
        ltitulo.setText("Buscar Pedido");

        javax.swing.GroupLayout playoutLayout = new javax.swing.GroupLayout(playout);
        playout.setLayout(playoutLayout);
        playoutLayout.setHorizontalGroup(
            playoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(playoutLayout.createSequentialGroup()
                .addGap(236, 236, 236)
                .addComponent(ltitulo)
                .addContainerGap(261, Short.MAX_VALUE))
        );
        playoutLayout.setVerticalGroup(
            playoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(playoutLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ltitulo)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        playout2.setBackground(new java.awt.Color(102, 102, 255));

        javax.swing.GroupLayout playout2Layout = new javax.swing.GroupLayout(playout2);
        playout2.setLayout(playout2Layout);
        playout2Layout.setHorizontalGroup(
            playout2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 646, Short.MAX_VALUE)
        );
        playout2Layout.setVerticalGroup(
            playout2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 19, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(playout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(playout2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(lpedido)
                .addGap(18, 18, 18)
                .addComponent(tpedido, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(buscarpedido)
                .addContainerGap(63, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 616, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(playout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lpedido)
                    .addComponent(tpedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscarpedido))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(playout2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

private void buscarpedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarpedidoActionPerformed

    preencher5();
    // TODO add your handling code here:
}//GEN-LAST:event_buscarpedidoActionPerformed

private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
// pegando na tabela a linha selecionada e enviendo para o formulario FinalPedido
    FFinalPedido.getinstacia().setVisible(true);
    int linha = jTable1.getSelectedRow();
   JFinalPedido.tnomeclientefinal.setText(jTable1.getValueAt(linha, 0).toString());
   JFinalPedido.tnumeromesafinal.setText(jTable1.getValueAt(linha, 1).toString());
   JFinalPedido.tdescricaofinal.setText(jTable1.getValueAt(linha,2 ).toString());
   preencher3();
   //JFinalPedido.tabelaprodutosfinal.setText(jTable1.getValueAt(linha, 3).toString());
   JFinalPedido.thorafinal.setText(jTable1.getValueAt(linha, 4).toString());
   JFinalPedido.tdatafinal.setText(jTable1.getValueAt(linha, 5).toString());
    // TODO add your handling code here:
   
}//GEN-LAST:event_jTable1MouseClicked
public void preencher5() { //função para Preencher a tabela com a busca por numero da mesa

        DefaultTableModel tab = (DefaultTableModel) jTable1.getModel();
        tab.setNumRows(0);

        try {
            Connection con = (Connection) ConectaBanco.getConexao();
            
            PreparedStatement pstmt;
            pstmt = (PreparedStatement) con.prepareStatement("select clientes.nome,pedidos.mesa,pedidos.descricao,item_cardapio.nome,pedidos.hora,pedidos.data"+
            " from pedidos"+
	" inner join clientes on pedidos.cliente = clientes.codigo"+
	" inner join iten_pedidos on pedidos.codigo = iten_pedidos.pedido"+
	" inner join item_cardapio on iten_pedidos.item_cardapio = item_cardapio.codigo"+
        " where pedidos.mesa = ?;" );

            pstmt.setString(1, tpedido.getText() );
            
            ResultSet rs = pstmt.executeQuery();
            
            while (rs.next()){   //inserindo na tabela 
                String cliente = rs.getString("clientes.nome");
                int mesa = rs.getInt("pedidos.mesa");
                String descricao = rs.getString("pedidos.descricao");
                String produto = rs.getString("item_cardapio.nome");
                String hora = rs.getString("pedidos.hora");
                String data = rs.getString("pedidos.data");
            tab.addRow(new Object[]{cliente,new Integer(mesa),descricao,produto,hora,data});
            }

            pstmt.close();

        } catch (SQLException e) {
            System.out.println("ERRO" + e);
        }

    }
public void preencher3(){ // selecionando um linha na tabela.
    int linha = jTable1.getSelectedRow();
    DefaultTableModel modelo = (DefaultTableModel)JFinalPedido.tabelaprodutosfinal.getModel();
       
    modelo.addRow(new Object[]{jTable1.getValueAt(linha, 3).toString()});
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buscarpedido;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lpedido;
    private javax.swing.JLabel ltitulo;
    private javax.swing.JPanel playout;
    private javax.swing.JPanel playout2;
    private javax.swing.JTextField tpedido;
    // End of variables declaration//GEN-END:variables
}
