/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JLogin.java
 *
 * Created on 25/11/2011, 15:39:58
 */
package gui.pizzaria;

import br.pizzaria.Funcionarios;
import dados.pizzaria.FuncionariosDao;
import dados.pizzaria.PizzariaDao;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Hugo Santos
 */
public class JLogin extends javax.swing.JPanel {
    public static Funcionarios f = new Funcionarios();
    /** Creates new form JLogin */
    public JLogin() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ltitulo = new javax.swing.JLabel();
        lusuario = new javax.swing.JLabel();
        tusuario = new javax.swing.JTextField();
        lsenha = new javax.swing.JLabel();
        senha = new javax.swing.JPasswordField();
        acessar = new javax.swing.JButton();

        ltitulo.setFont(new java.awt.Font("Tahoma", 0, 18));
        ltitulo.setText("Acesso ao Sistema");

        lusuario.setText("Usuario:");

        lsenha.setText("Senha:");

        acessar.setText("Acessar");
        acessar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acessarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(80, Short.MAX_VALUE)
                .addComponent(ltitulo)
                .addGap(77, 77, 77))
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lusuario)
                    .addComponent(lsenha))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(senha)
                    .addComponent(tusuario, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE))
                .addContainerGap(101, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(222, Short.MAX_VALUE)
                .addComponent(acessar)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ltitulo)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lusuario)
                            .addComponent(tusuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lsenha)
                            .addComponent(senha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(32, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(acessar)
                        .addGap(56, 56, 56))))
        );
    }// </editor-fold>//GEN-END:initComponents

private void acessarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acessarActionPerformed
   //String a, b;
   
   FuncionariosDao fDao = PizzariaDao.novoFuncionariosDao();
   
   ArrayList<Funcionarios> fl = new ArrayList<Funcionarios>();
    //pegando os campos
   f.setUsuario(tusuario.getText());
   //criptografando a senha para comparação
   f.setSenha(FuncionariosDao.criptografa( senha.getText()));
   
   //JOptionPane.showMessageDialog(null,FuncionariosDao.criptografa( senha.getText()));
   //buscando do banco de dados e testando
   fl = fDao.buscar(f);
   if(fl.isEmpty()){
       JOptionPane.showMessageDialog(null, " Usuario Incorreto e Senha Incorreto.");
       return ;
   }
   f.setCodigo(fl.get(0).getCodigo());
//abrindo o formulario principal
   FPrincipal.getinstacia().setVisible(true);
   //   
//    if(tusuario.getText() == a && senha.getText() ==  b){
//        FPrincipal.getinstacia().setVisible(true);
//    }
//    else{
//        
//    }
    
    // TODO add your handling code here:
}//GEN-LAST:event_acessarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton acessar;
    private javax.swing.JLabel lsenha;
    private javax.swing.JLabel ltitulo;
    private javax.swing.JLabel lusuario;
    private javax.swing.JPasswordField senha;
    private javax.swing.JTextField tusuario;
    // End of variables declaration//GEN-END:variables
}
